### ISSUE TITLE
Still getting 64bit error

### ISSUE THREAD

**Issue by necov** [bguidolim/TiNowPlaying#6]
Hello, 

Despite having downloaded the 64bit supported version, I still get this error:
[ERROR] [iphone, 8.1, undefined] Couldn't find module: com.guidolim.tinowplaying for architecture: x86_64

**Comment by bguidolim** [comment]
Did you download using this link?

https://github.com/bguidolim/TiNowPlaying/blob/master/dist/com.guidolim.tinowplaying-iphone-1.2.zip

**Comment by necov** [comment]
Hi,

Yes I used that link. Still gets the x86_64 error.

**Comment by necov** [comment]
And this is using SDK 3.5.0

**Comment by necov** [comment]
Hello?

**Comment by bguidolim** [comment]
Hi!

I've checked the module using it: http://docs.appcelerator.com/titanium/release-notes/?version=3.5.0.GA#modules

This is the output:
![screen shot 2015-02-03 at 3 13 26 pm](https://cloud.githubusercontent.com/assets/987360/6025151/5f6afae2-abb7-11e4-8390-ed06aa32f45a.png)

So, let me ask: Have you set correct version in your tiapp.xml?

**Comment by necov** [comment]
Hi :-)

My tiapp.xml states <sdk-version>3.5.0.GA</sdk-version> - If you want, I can copy my whole tiapp.xml. I've also tried running the xcrun, and i get the same output as you..

**Comment by necov** [comment]
Got it to work - Thanks!! :)

**Comment by bguidolim** [comment]
@necov what it was?
