### ISSUE TITLE
Issue when locking screen

### ISSUE THREAD

**Issue by christianrockbryan** [bguidolim/TiNowPlaying#7]
I am currently using the TiNowPlaying Titanium module with my app and it works great.  However, I am trying to add 64bit support and the app crashes because of this module.  I have upgraded to version 1.2, but that did not help.  My app is a online radio app called ChristianRock.Net.

What happens is when I load the app and run it, the music and all functions work well.  However, when I lock the screen, the app crashes with this error message:

[ERROR] :  The application has crashed with an uncaught exception 'NSInvalidArgumentException'.
[ERROR] :  Reason:
[ERROR] :  -[__NSCFType onBackground:]: unrecognized selector sent to instance 0x136e22c90
[ERROR] :  Stack trace:
[ERROR] :  
[ERROR] :  0   CoreFoundation                      0x0000000182712530 <redacted> + 132
[ERROR] :  1   libobjc.A.dylib                     0x00000001936f00e4 objc_exception_throw + 60
[ERROR] :  2   CoreFoundation                      0x00000001827195f4 <redacted> + 0
[ERROR] :  3   CoreFoundation                      0x00000001827163ac <redacted> + 928
[ERROR] :  4   CoreFoundation                      0x000000018261ac4c _CF_forwarding_prep_0 + 92
[ERROR] :  5   CoreFoundation                      0x00000001826b8ddc <redacted> + 20
[ERROR] :  6   CoreFoundation                      0x00000001825f7370 _CFXNotificationPost + 2060
[ERROR] :  7   Foundation                          0x000000018351b520 <redacted> + 72
[ERROR] :  8   UIKit                               0x00000001871ae92c <redacted> + 856
[ERROR] :  9   UIKit                               0x00000001871b7084 <redacted> + 92
[ERROR] :  10  UIKit                               0x00000001871b700c <redacted> + 380
[ERROR] :  11  UIKit                               0x00000001871aa6a8 <redacted> + 512
[ERROR] :  12  FrontBoardServices                  0x000000018abd1604 <redacted> + 28
[ERROR] :  13  CoreFoundation                      0x00000001826cad70 <redacted> + 20
[ERROR] :  14  CoreFoundation                      0x00000001826c9e78 <redacted> + 312
[ERROR] :  15  CoreFoundation                      0x00000001826c849c <redacted> + 1756
[ERROR] :  16  CoreFoundation                      0x00000001825f51f4 CFRunLoopRunSpecific + 396
[ERROR] :  17  GraphicsServices                    0x000000018ba176fc GSEventRunModal + 168
[ERROR] :  18  UIKit                               0x0000000186f8610c UIApplicationMain + 1488
[ERROR] :  19  ChristianRock                       0x0000000100042f20 ChristianRock + 28448
[ERROR] :  20  libdyld.dylib                       0x0000000193d6ea08 <redacted> + 4
[ERROR] :  **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFType onBackground:]: unrecognized selector sent to instance 0x136e22c90'
[ERROR] :  **\* First throw call stack:
[ERROR] :  (0x182712530 0x1936f00e4 0x1827195f4 0x1827163ac 0x18261ac4c 0x1826b8ddc 0x1825f7370 0x18351b520 0x1871ae92c 0x1871b7084 0x1871b700c 0x1871aa6a8 0x18abd1604 0x1826cad70 0x1826c9e78 0x1826c849c 0x1825f51f4 0x18ba176fc 0x186f8610c 0x100042f20 0x193d6ea08)

If there is anything you can do to help me I would appreciate it.  We need to get an update out around April first with updated graphics and we cannot submit it to Apple until this is fixed, since all app updates have to be 64 bit now.

**Comment by bguidolim** [comment]
Try to remove the module and comment all references of the module and see if this errors occurs again.
I'm wondering if it's happening really about the module.

Let me know if it works.

**Comment by christianrockbryan** [comment]
You are right.  Thank you.  I haven't fixed it 
yet, but I have eliminated this module.

Have a great day!
Bryan Whitaker

At 11:05 AM 3/16/2015, you wrote:
